module.exports = [
    {
        method:'POST',
        path:'/api/aritcle'
    },
    {
        method:'PUT',
        path:'/api/aritcle/:id'
    },
    {
        method:'DELETE',
        path:'/api/aritcle/:id'
    },
    {
        method:'POST',
        path:'/api/aritcleType'
    },
    {
        method:'PUT',
        path:'/api/aritcleType/:id'
    },
    {
        method:'DELETE',
        path:'/api/aritcleType/:id'
    },
    {
        method:'PUT',
        path:'/api/comment/:id'
    },
    {
        method:'DELETE',
        path:'/api/comment/:id'
    },
    {
        method:'PUT',
        path:'/api/config'
    },
    {
        method:'POST',
        path:'/api/everyDay'
    },
    {
        method:'PUT',
        path:'/api/everyDay/:id'
    },
    {
        method:'DELETE',
        path:'/api/everyDay/:id'
    },
    {
        method:'POST',
        path:'/api/firstPage'
    },
    {
        method:'PUT',
        path:'/api/firstPage/:id'
    },
    {
        method:'DELETE',
        path:'/api/firstPage/:id'
    },
    {
        method:'POST',
        path:'/api/secondPage'
    },
    {
        method:'PUT',
        path:'/api/secondPage/:id'
    },
    {
        method:'DELETE',
        path:'/api/secondPage/:id'
    },
    {
        method:'POST',
        path:'/api/label'
    },
    {
        method:'PUT',
        path:'/api/label/:id'
    },
    {
        method:'DELETE',
        path:'/api/label/:id'
    },
    {
        method:'POST',
        path:'/api/page'
    },
    {
        method:'PUT',
        path:'/api/page/:id'
    },
    {
        method:'DELETE',
        path:'/api/page/:id'
    },
    {
        method:'PUT',
        path:'/api/reply/:id'
    },
    {
        method:'DELETE',
        path:'/api/reply/:id'
    },
    {
        method:'PUT',
        path:'/api/user'
    },
    {
        method:'POST',
        path:'/api/user/whoami'
    },
]